# Generated by Django 4.2.6 on 2023-10-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteNest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
